

//HERE SO THAT WE DO NOT HAVE MULTIPLE DEFINITION ERRORS
// JUST USE THE INCLUDE WITHOUT THE MACRO

#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include <stb_truetype.h>
